name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # Trigger deployment on push to the "main" branch. Change to "master" if needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'   # Ensure you're using a compatible version of Node.js
        cache: 'yarn'

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Build the React app
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Access GitHub token for deployment
        publish_dir: ./build   # Directory to deploy (default output for React build)
